# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 35dc063
_src_path: gh:makukha/copython
author_email: m.makukha@gmail.com
author_name: Michael Makukha
copyright_year: 2025
docs: readthedocs
docs_url: https://doctestcase.rtfd.io
github_slug: makukha/doctestcase
github_url: https://github.com/makukha/doctestcase
module_name: doctestcase
opessf_bp_id: '10377'
project_name: doctestcase
project_version: 0.2.2
pypi_package_name: doctestcase
pypi_url: https://pypi.org/project/doctestcase
python_version: 3.13.2
python_version_minor: '3.13'
readthedocs_tool: sphinx
