from typing import Any, ClassVar
from unittest import TestCase

class DocTestCase(TestCase):
    globs: ClassVar[dict[str, Any]]
    opts: ClassVar[int]

    def __init_subclass__(cls, globs: dict[str, Any], opts: int) -> None: ...
    def test0(self) -> None: ...
    @classmethod
    def doc_markdown(cls, title_depth: int) -> str: ...
    @classmethod
    def doc_rest(cls, title_char: str) -> str: ...
